# Generated by Django 5.1.5 on 2025-01-27 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField()),
                ('category', models.CharField(max_length=100)),
                ('image', models.URLField()),
                ('sold', models.BooleanField()),
                ('is_sale', models.BooleanField()),
                ('date_of_sale', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
